### ISSUE TITLE
Links to figures are broken

### ISSUE THREAD

**Issue by iamyajat** [shubhamhackz/flutter-ninja#3]
Links to a lot of figures are broken.
Example: [Route Management](https://github.com/shubhamhackz/flutter-ninja/blob/main/manuscript/chapter_2.2.md#221-a-simple-example)

**Comment by shubhamhackz** [comment]
Links to Images are fixed with this pull request : https://github.com/shubhamhackz/flutter-ninja/pull/6#issue-703587146
