### ISSUE TITLE
Add syntax highlights

### ISSUE THREAD

**Issue by TimWhiting** [shubhamhackz/flutter-ninja#4]
For markdown you can add dart syntax highlighting by typing dart after the triple back ticks that delimit the code block.
\```dart
Code here 
\```

```dart
void main() {
  final hi = 'Hello World';
}
```

**Comment by shubhamhackz** [comment]
Will do it. In the meantime you can also do pull requests.

**Comment by caffeineflo** [comment]
Looks like this has been resolved with 648ab8703b8318232e5bb2bd5b680625deaf122d and can be closed
